name: ObjectFormat CI

on:
  push:
    branches:
      - main
  release:
    types: [ published, created, edited ]
permissions:
  packages: write

jobs:
  test-on-jdk11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: install depends
        run: chmod +x gradlew && ./gradlew tasks
      - name: Test with Gradle
        run: chmod +x gradlew && ./gradlew clean test
  test-on-jdk17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: install depends
        run: chmod +x gradlew && ./gradlew tasks
      - name: Test with Gradle
        run: chmod +x gradlew && ./gradlew clean test
